# Generated by Django 5.0.2 on 2024-11-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('usn', models.CharField(max_length=10)),
                ('mobile', models.IntegerField()),
                ('course', models.TextField()),
            ],
        ),
    ]
