# Generated by Django 5.0.2 on 2024-11-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('processor', models.CharField(max_length=20)),
                ('memory', models.IntegerField()),
                ('screen_size', models.IntegerField()),
            ],
        ),
    ]
