# Generated by Django 5.0.2 on 2024-11-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
